parameters:
    ferrandini.pdo.db_options:
        db_table:    Session
        db_id_col:   id
        db_data_col: value
        db_time_col: time

services:
    ferrandini.pdo:
        class: PDO
        arguments:
            dsn:     "mysql:host=%database_host%;port=%database_port%;dbname=%database_name%"
            user:     %database_user%
            password: %database_password%
        calls:
            - [setAttribute, [3, 2]] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

    ferrandini.pdo.session.handler:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: ["@ferrandini.pdo", "%ferrandini.pdo.db_options%"]